sonar.organization=matheo691200-sudo
sonar.projectKey=matheo691200-sudo_webapp
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
